pipeline {
    agent any
    
    environment {
        DOCKER_PATH = '/usr/local/bin/docker' // Path to Docker binary on macOS
        DOCKER_TAG = "mishan202/nodeapp-cuban:${BUILD_NUMBER}" // Docker image tag
    }

    stages {
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    git branch: 'main', url: 'https://github.com/Mishan20/GitHub-Docker-and-Jenkins-CI-CD-Pipeline.git'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                sh '${DOCKER_PATH} build -t ${DOCKER_TAG} .'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'test-dockerhubpassword', variable: 'testdockerpsswd')]) {
                    script {
                        sh "${DOCKER_PATH} login -u mishan202 -p '${testdockerpsswd}'"
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                sh "${DOCKER_PATH} push ${DOCKER_TAG}"
            }
        }
    }

    post {
        always {
            sh '${DOCKER_PATH} logout || echo "Logout failed (non-critical)"'
        }
    }
}