pipeline {
    agent any
    environment {
        DOCKER_TAG = 'mishan202/nodeapp:v1' // Replace with your Docker image tag
    }

    stages {
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    git branch: 'main', url: 'https://github.com/Mishan20/GitHub-Docker-and-Jenkins-CI-CD-Pipeline.git'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${DOCKER_TAG} .'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'test-dockerhubpassword', variable: 'testdockerpsswd')]) {
                    sh 'docker login -u mishan202 -p ${testdockerpsswd}'
                }
            }
        }
        stage('Push Image') {
            steps {
                sh 'docker push ${DOCKER_TAG}'
            }
        }
    }

    post {
        always {
            sh 'docker logout || echo "Logout failed (non-critical)"'
        }
    }
}